return {
  { id = "allinyourname", title = "All In Your Name MV Michael Jackson", fps = 12 },
  { id = "backrooms_2", title = "Backrooms Found Footage #2", fps = 12 },
  { id = "backrooms_3", title = "Backrooms Found Footage #3", fps = 12 },
  { id = "backroomstrailerkane", title = "Backrooms Trailer Kane Pixels", fps = 12 },
  { id = "benjaminarch", title = "Benjamin vs Archanine", fps = 12 },
  { id = "benjaminichimaru", title = "Benjamin vs Ichimaru", fps = 12 },
  { id = "benjaminluther", title = "Benjamin vs Luther", fps = 12 },
  { id = "benjaminmicwizard", title = "Benjamin vs Mic Wizard", fps = 12 },
  { id = "benjaminpivot", title = "Benjamin vs Pivot Blimp", fps = 12 },
  { id = "conquesttest", title = "Conquest Arrival High FPS", fps = 22 },
  { id = "conquestvsinvincible_p01", title = "Conquest vs Invincible (ULTRA HIGH FPS) Part 1", fps = 30 },
  { id = "conquestvsinvincible_p02", title = "Conquest vs Invincible (ULTRA HIGH FPS) Part 2", fps = 30 },
  { id = "conquestvsinvincible_p03", title = "Conquest vs Invincible (ULTRA HIGH FPS) Part 3", fps = 30 },
  { id = "conquestvsinvincible_p04", title = "Conquest vs Invincible (ULTRA HIGH FPS) Part 4", fps = 30 },
  { id = "conquestvsinvincible_p05", title = "Conquest vs Invincible (ULTRA HIGH FPS) Part 5", fps = 30 },
  { id = "conquestvsinvincible_p06", title = "Conquest vs Invincible (ULTRA HIGH FPS) Part 6", fps = 30 },
  { id = "conquestsuperman", title = "Conquest vs Superman", fps = 12 },
  { id = "thedeep1", title = "Deep Thoughts with The Deep (ULTRA HIGH FPS)", fps = 45 },
  { id = "thedeep2", title = "Deep Thoughts with The Deep 2 (ULTRA HIGH FPS)", fps = 45 },
  { id = "thedeep3", title = "Deep Thoughts with The Deep 3 (ULTRA HIGH FPS)", fps = 45 },
  { id = "diegojean", title = "Diego Lopes vs Jean Silva", fps = 12 },
  { id = "grogofucku", title = "Grogu Mandalorian Trailer", fps = 12 },
  { id = "homelandercrashout", title = "Homelander Crashout Comp", fps = 12 },
  { id = "homelanderblindspot", title = "Homelander meets Blindspot (ULTRA HIGH FPS)", fps = 45 },
  { id = "ilia1", title = "Ilia Topuria vs Charles Oliveria", fps = 12 },
  { id = "nemesis_mission_revenge", title = "NEMESIS Mission: REVENGE", fps = 12 },
  { id = "nettspend_ft_osamason_wake_up_mv", title = "Nettspend ft. OsamaSon - Wake Up MV", fps = 12 },
  { id = "nettspend_shutup_mv", title = "Nettspend Shutup MV", fps = 12 },
  { id = "omnimaninvincible", title = "Omniman vs. The Guardians of the Globe (ULTRA HIGH FPS)", fps = 30 },
  { id = "osamason_ref", title = "Osamason - Ref MV", fps = 12 },
  { id = "osamason_demon_home_mv", title = "Osamason Demon Home MV", fps = 12 },
  { id = "scp_096_homelander", title = "SCP 096 vs Homelander", fps = 12 },
  { id = "omnimanscp", title = "SCP 096 vs Omniman", fps = 12 },
  { id = "scp_096_vs_thragg", title = "SCP 096 vs Thragg", fps = 12 },
  { id = "soldierboy1", title = "Soldier Boy Clip", fps = 12 },
  { id = "summrs_prove_sum_mv", title = "summrs - prove sum MV", fps = 12 },
}
